---
title: "Long-term *Ipomopsis* Floral Volatiles"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>

```{r setup, message=FALSE}
library(tidyverse)
library(pheatmap)
library(dendsort)
library(viridis)
library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, 
                      fig.path = "images/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=8, fig.width=8)
options(digits=4, knitr.kable.NA = "") # for kables
```

```{r load_metadata}
metadata <- list.files("data/volatiles", pattern = "Ipomopsis long-term volatiles - 20", full.names=T) %>% 
  map_dfr(~read_tsv(.x, show_col_types = F) %>% 
            mutate(across(any_of(c("pump_id", "plant", "vial", "sample")), as.character)), .id="metafile") %>% 
  mutate(year = year(date))

# metadata %>% add_count(year, date, time, site, type, sample) %>% filter(n>1) %>% 
#   arrange(year, date, time, site, type, sample) %>% write_tsv("data/volatiles/metadupes.tsv", na="")
```

# Field metadata

```{r plot_metadata}
ggplot(metadata, aes(x=yday(date), fill=paste(site, time))) + 
  facet_wrap(vars(year), ncol=1) + geom_bar() +
  scale_fill_brewer(palette = "Paired") + theme_classic() + 
  labs(x="Day of year", y="Samples", fill="Site, time")

metadata %>% filter(type=="floral") %>% count(year, site, time) %>% 
  pivot_wider(names_from=c("site","time"), values_from="n") %>% kable(caption = "floral samples")
metadata %>% filter(type=="ambient") %>% count(year, site, time) %>% 
  pivot_wider(names_from=c("site","time"), values_from="n") %>% kable(caption = "ambient samples")
metadata %>% filter(type=="floral") %>% count(year, site, time, plant) %>% count(year, site, time) %>% 
  pivot_wider(names_from=c("site","time"), values_from="n") %>% kable(caption = "plants")

left_join(metadata %>% filter(type=="floral") %>% count(year, site, time, name="samples"),
          metadata %>% filter(type=="floral") %>% count(year, site, time, plant) %>% count(year, site, time, name="plants")) %>% 
  mutate(samples_per_plant = samples/plants, .keep="unused") %>% 
    pivot_wider(names_from=c("site","time"), values_from="samples_per_plant") %>% kable(caption = "samples per plant")
```

## Soil moisture

```{r soil_moisture}
metadata %>% filter(type=="floral") %>% group_by(year, site, time, date) %>% summarize(has_VWC = mean(!is.na(VWC))) %>% 
  ggplot(aes(y=fct_rev(paste(date, site, time)), color=paste(site, time), x=has_VWC)) + geom_point(size=3) +
  scale_color_brewer(palette = "Paired") + theme_minimal() + 
  labs(x="Fraction of floral samples with soil moisture recorded", y="Date, site, time", color="Site, time")

ggplot(metadata, aes(x=yday(date), color=paste(site, time), y=VWC)) + 
  facet_wrap(vars(year), ncol=1) + geom_point() +
  scale_color_brewer(palette = "Paired") + theme_classic() + 
  labs(x="Day of year", y="Soil moisture", color="Site, time")

ggplot(metadata, aes(x=site, fill=paste(site, time), y=VWC)) + 
  facet_wrap(vars(year), nrow=1) + geom_boxplot(outlier.size=0.5) +
  scale_fill_brewer(palette = "Paired") + theme_classic() + 
  labs(x="Site", y="Soil moisture", fill="Site, time")
```

## Extraction time

```{r time}
ggplot(metadata, aes(x=site, fill=paste(site, time), y=bag)) + 
  facet_grid(time~year, scales = "free_y") + geom_boxplot(outlier.size=0.5) +
  scale_fill_brewer(palette = "Paired") + theme_minimal() + 
  labs(x="Site", y="Bag time", fill="Site, time")

ggplot(metadata, aes(x=site, fill=paste(site, time), y=(pump-bag)/60)) + 
  facet_wrap(vars(year), nrow=1) + geom_boxplot(outlier.size=0.5) +
  scale_fill_brewer(palette = "Paired") + theme_minimal() + 
  labs(x="Site", y="Equilibration time (min)", fill="Site, time")

ggplot(metadata, aes(x=site, fill=paste(site, time), y=(end-pump)/60)) + 
  facet_wrap(vars(year), nrow=1) + geom_boxplot(outlier.size=0.5) +
  scale_fill_brewer(palette = "Paired") + theme_minimal() + 
  labs(x="Site", y="Pumping time (min)", fill="Site, time")
```

# Matching field metadata and filenames

```{r plot_matching}
filemeta <- read_csv("data/volatiles/Ipomopsis GCMS files - ipo_meta_split.csv") %>% 
  filter(type != "blank", #GC blank
         !verdict %in% c("skip-notrun", #tube was skipped by the autosampler
                         "leak-blank", #tube leaked, not desorbed but GC run anyway
                         "mismatch-leak", #tube leaked, tube time not aligned with file time
                         "skip-rename-mismatch-leak", #tube leaked after skip, tube time not aligned with file time
                         "filemoved" #file was moved on disk so creation time is wrong
         )) %>% drop_na(type, FileName) %>%  #no file match to desorb start time
  distinct(FileName, .keep_all = T) %>% #some files got duplicated from fuzzy matching times
  mutate(date = ymd(date), year=year(date), vial=as.character(vial))

#TODO figure out which of these dupes has the real sample
filemeta %>% add_count(year, date, time, site, type, sample) %>% filter(n>1) %>% 
  arrange(year, date, time, site, type, sample) %>% write_tsv("data/volatiles/filedupes.tsv", na="")
#until then, use only the first duplicate
filemeta <- filemeta %>% distinct(year, date, time, site, type, sample, .keep_all=T)

bind_rows(files=filemeta, field=metadata, .id="source")%>%  
  ggplot(aes(y=paste(date, site, time), fill=source)) + 
  geom_bar(position=position_dodge(width=0.4)) + 
  scale_fill_brewer(palette = "Set2") + theme_classic() + 
  labs(y="Date, site, time", x="Samples", fill="Source")

full_join(count(filemeta, type, name="files"), count(metadata, type, name="field")) %>% kable()

full_join(count(filemeta, year, date, time, site, name="files"), 
          count(metadata, year, date, time, site, name="field")) %>% kable()
```

```{r matching}
library(tidylog)
meta.full <- full_join(mutate(filemeta, files=1), 
                  mutate(metadata, field=1), by=c("year", "date", "time", "site", "type", "sample")) %>% 
  mutate(files=replace_na(files, 0), field=replace_na(field, 0), match = files==1 & field==1)

meta.full %>% filter(match==F) %>% arrange(date, time, site, field, files) %>% 
  select(date, time, site, type, field, files, sample, 
         rundate, samplename, vial.x, vial.y, split_notes, notes) %>% 
  write_tsv("data/volatiles/matching.tsv", na="")

meta.full %>% group_by(year, date, time, site) %>% 
  summarize(across(c(files, field, match), mean)) %>% 
  mutate(files=files-match, field=field-match) %>% 
  pivot_longer(c(files, field, match)) %>% 
  mutate(name=factor(name, levels=c("files", "match", "field"))) %>% 
  ggplot(aes(y=paste(date, site, time), x=value, fill=name)) + geom_col() +
  labs(x="",y="", fill="") + theme_minimal()
```

# Samples vs. controls

```{r ipochems}
# load short names 
ipochems <- read_csv("data/volatiles/Ipo volatile compounds - chemsf_ipo.csv") %>% 
  select(name, shortname, standard, verdict) %>%  filter(verdict != "") %>% 
  mutate(standard = fct_recode(standard, "Methyl_salicylate"="Benzaldehyde"), # benzaldehyde regressions not reliable
         class = fct_recode(standard, Aliphatics="Hexenol", Benzenoids="Methyl_salicylate", Benzenoids="Indole", 
                            Sesquiterpenes="Caryophyllene", Monoterpenes="alpha_Pinene", Monoterpenes="Linalool")) %>%  
  left_join(read_csv("data/volatiles/regressions_181921_filtered_slopes.csv") %>% 
              pivot_wider(id_cols=standard, names_from="year", names_prefix="area_per_ng", values_from=area_per_ng)) 
class_pal <- set_names(c("#BC0060","#027B8C","#E56E00","#86D400"), levels(ipochems$class))

#shorten chemical names and merge compounds with multiple names
shortnames <- ipochems %>% select(name, shortname) %>% filter(shortname!="") %>% deframe()
#shortnames[shortnames %in% shortnames[duplicated(shortnames)]]

greekify <- function(names) {
  names %>% 
    str_replace("^a-","\U03B1-") %>% str_replace("-a-","-\U03B1-") %>% 
    str_replace("^b-","\U03B2-") %>% str_replace("-b-","-\U03B2-") %>% 
    str_replace("^g-","\U03B3-") %>% str_replace("-g-","-\U03B3-")
}
```


```{r quant}
source("read_shimadzu.R")
quant.full <- list.files("data/volatiles/quant/", full.names = T) %>% 
  map_dfr(read.shimadzu.quant) %>%
  mutate(Name = trimws(Name), Area=replace_na(Area, 0)) %>% 
  distinct(Filename, Name, .keep_all=T)

setdiff(quant.full$Filename, meta.full$FileName)#TODO no metadata, consider filling some in
setdiff(meta.full$FileName, quant.full$Filename)#TODO need to find and integrate these

#only keep file-metadata matches
files.match <- intersect(meta.full$FileName, quant.full$Filename)
meta.all   <- meta.full %>% filter(FileName %in% files.match)
quant.all <- quant.full %>% filter(Filename %in% files.match) %>%
  select(Filename, Name, Area) %>%
  mutate(Name = recode(Name, !!!shortnames)) %>%
  pivot_wider(names_from = "Name", values_from="Area") %>% 
  arrange(match(Filename, meta.all$FileName)) %>% 
  write_tsv("data/volatiles/quant_all.tsv") %>% 
  as.data.frame() %>% column_to_rownames("Filename")
```

```{r quant_heatmap, dev="png", dev.args=list(),fig.width=16, fig.height=12}
# annot_pal <- list(
#   year_run = set_names(brewer.pal(8, "Set1")[1:length(unique(meta.all$year_run))], unique(meta.all$year_run)),
#   type = set_names(brewer.pal(8, "Set1")[1:length(unique(meta.all$type))], unique(meta.all$type)))
pheatmap(as.matrix(t(quant.all))^(1/4), 
         cluster_cols=F, show_colnames=F,
         clustering_method="mcquitty", clustering_distance_rows="correlation",
         clustering_callback = function(hc, ...){dendsort(hc, type="average")},
         # annotation_col=meta.all %>% select(year_run) %>% mutate(across(everything(), factor)),
         # annotation_colors =  annot_pal,
         scale="none", color=mako(512),main="Quant volatiles")
```

